### ISSUE TITLE
Email required for identity error

### ISSUE THREAD

**Issue by alsoicode** [adamreisnz/sendgrid-mailer#6]
Hello,

I'm getting an error from line 103 in index.js stating "Email required for identity". Here is how I'm creating my email data:

    const emailData = {
      to: 'nothing@nowhere.com',
      from: 'no-reply@client.com',
      bcc: ['address1@gmail.com', 'address2@gmail.com'],
      subject: campaign.title,
      text: campaign.email.textContent,
      html: campaign.email.htmlContent,
    };

    const email = sendGridMailer.createEmail(emailData);

What am I doing wrong?

**Comment by adamreisnz** [comment]
Can you tell me what it mentions after that error message? It should append the string/contents that was passed in the error message. That should help identify where the problem lies.

**Comment by adamreisnz** [comment]
Ah, sorry I see it now. You are using the wrong method to create the mail.

You have to use `createMail` instead of `createEmail`. The former creates a mail object, the latter creates an email object which is only name + email address.

The naming is confusing, I know, but that's what they used at Sendgrid.

**Comment by alsoicode** [comment]
Thanks Adam, that's got me going again.
